//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.03 at 01:32:53 PM MESZ 
//


package de.thorstenberger.taskmodel.complex.complextaskdef;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://complex.taskmodel.thorstenberger.de/complexTaskDef}SubTaskDefType">
 *       &lt;sequence>
 *         &lt;element name="displayedAnswers">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="correct" maxOccurs="unbounded">
 *             &lt;complexType>
 *               &lt;simpleContent>
 *                 &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                   &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;/extension>
 *               &lt;/simpleContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="incorrect" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;simpleContent>
 *                 &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                   &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;/extension>
 *               &lt;/simpleContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="category" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="singleSelect"/>
 *             &lt;enumeration value="multipleSelect"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="minCorrectAnswers">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="maxCorrectAnswers" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="preserveOrderOfAnswers" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "displayedAnswers",
    "correctOrIncorrect"
})
@XmlRootElement(name = "mcSubTaskDef")
public class McSubTaskDef
    extends SubTaskDefType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected int displayedAnswers;
    @XmlElements({
        @XmlElement(name = "incorrect", type = McSubTaskDef.Incorrect.class),
        @XmlElement(name = "correct", type = McSubTaskDef.Correct.class)
    })
    protected List<Serializable> correctOrIncorrect;
    @XmlAttribute(required = true)
    protected String category;
    @XmlAttribute
    protected Integer minCorrectAnswers;
    @XmlAttribute
    protected Integer maxCorrectAnswers;
    @XmlAttribute
    protected Boolean preserveOrderOfAnswers;

    /**
     * Gets the value of the displayedAnswers property.
     * 
     */
    public int getDisplayedAnswers() {
        return displayedAnswers;
    }

    /**
     * Sets the value of the displayedAnswers property.
     * 
     */
    public void setDisplayedAnswers(int value) {
        this.displayedAnswers = value;
    }

    public boolean isSetDisplayedAnswers() {
        return true;
    }

    /**
     * Gets the value of the correctOrIncorrect property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the correctOrIncorrect property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCorrectOrIncorrect().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link McSubTaskDef.Incorrect }
     * {@link McSubTaskDef.Correct }
     * 
     * 
     */
    public List<Serializable> getCorrectOrIncorrect() {
        if (correctOrIncorrect == null) {
            correctOrIncorrect = new ArrayList<Serializable>();
        }
        return this.correctOrIncorrect;
    }

    public boolean isSetCorrectOrIncorrect() {
        return ((this.correctOrIncorrect!= null)&&(!this.correctOrIncorrect.isEmpty()));
    }

    public void unsetCorrectOrIncorrect() {
        this.correctOrIncorrect = null;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    public boolean isSetCategory() {
        return (this.category!= null);
    }

    /**
     * Gets the value of the minCorrectAnswers property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMinCorrectAnswers() {
        return minCorrectAnswers;
    }

    /**
     * Sets the value of the minCorrectAnswers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinCorrectAnswers(int value) {
        this.minCorrectAnswers = value;
    }

    public boolean isSetMinCorrectAnswers() {
        return (this.minCorrectAnswers!= null);
    }

    public void unsetMinCorrectAnswers() {
        this.minCorrectAnswers = null;
    }

    /**
     * Gets the value of the maxCorrectAnswers property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMaxCorrectAnswers() {
        return maxCorrectAnswers;
    }

    /**
     * Sets the value of the maxCorrectAnswers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxCorrectAnswers(int value) {
        this.maxCorrectAnswers = value;
    }

    public boolean isSetMaxCorrectAnswers() {
        return (this.maxCorrectAnswers!= null);
    }

    public void unsetMaxCorrectAnswers() {
        this.maxCorrectAnswers = null;
    }

    /**
     * Gets the value of the preserveOrderOfAnswers property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPreserveOrderOfAnswers() {
        if (preserveOrderOfAnswers == null) {
            return false;
        } else {
            return preserveOrderOfAnswers;
        }
    }

    /**
     * Sets the value of the preserveOrderOfAnswers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPreserveOrderOfAnswers(boolean value) {
        this.preserveOrderOfAnswers = value;
    }

    public boolean isSetPreserveOrderOfAnswers() {
        return (this.preserveOrderOfAnswers!= null);
    }

    public void unsetPreserveOrderOfAnswers() {
        this.preserveOrderOfAnswers = null;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Correct implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlValue
        protected String value;
        @XmlAttribute(required = true)
        protected String id;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        public boolean isSetValue() {
            return (this.value!= null);
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        public boolean isSetId() {
            return (this.id!= null);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Incorrect implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlValue
        protected String value;
        @XmlAttribute(required = true)
        protected String id;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        public boolean isSetValue() {
            return (this.value!= null);
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        public boolean isSetId() {
            return (this.id!= null);
        }

    }

}
