//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.03 at 01:32:53 PM MESZ 
//


package de.thorstenberger.taskmodel.complex.complextaskdef;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://complex.taskmodel.thorstenberger.de/complexTaskDef}SubTaskDefType">
 *       &lt;sequence>
 *         &lt;element name="images" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="mutableTemplateImage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="immutableBackgroundImage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="correctionTemplateImage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="textualAnswer" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="textFieldWidth" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                         &lt;minInclusive value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="textFieldHeight" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                         &lt;minInclusive value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="colorChangeable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="strokewidthChangeable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "images",
    "textualAnswer",
    "colorChangeable",
    "strokewidthChangeable"
})
@XmlRootElement(name = "paintSubTaskDef")
public class PaintSubTaskDef
    extends SubTaskDefType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected PaintSubTaskDef.Images images;
    protected PaintSubTaskDef.TextualAnswer textualAnswer;
    protected Boolean colorChangeable;
    protected Boolean strokewidthChangeable;

    /**
     * Gets the value of the images property.
     * 
     * @return
     *     possible object is
     *     {@link PaintSubTaskDef.Images }
     *     
     */
    public PaintSubTaskDef.Images getImages() {
        return images;
    }

    /**
     * Sets the value of the images property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaintSubTaskDef.Images }
     *     
     */
    public void setImages(PaintSubTaskDef.Images value) {
        this.images = value;
    }

    public boolean isSetImages() {
        return (this.images!= null);
    }

    /**
     * Gets the value of the textualAnswer property.
     * 
     * @return
     *     possible object is
     *     {@link PaintSubTaskDef.TextualAnswer }
     *     
     */
    public PaintSubTaskDef.TextualAnswer getTextualAnswer() {
        return textualAnswer;
    }

    /**
     * Sets the value of the textualAnswer property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaintSubTaskDef.TextualAnswer }
     *     
     */
    public void setTextualAnswer(PaintSubTaskDef.TextualAnswer value) {
        this.textualAnswer = value;
    }

    public boolean isSetTextualAnswer() {
        return (this.textualAnswer!= null);
    }

    /**
     * Gets the value of the colorChangeable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isColorChangeable() {
        return colorChangeable;
    }

    /**
     * Sets the value of the colorChangeable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setColorChangeable(Boolean value) {
        this.colorChangeable = value;
    }

    public boolean isSetColorChangeable() {
        return (this.colorChangeable!= null);
    }

    /**
     * Gets the value of the strokewidthChangeable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStrokewidthChangeable() {
        return strokewidthChangeable;
    }

    /**
     * Sets the value of the strokewidthChangeable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStrokewidthChangeable(Boolean value) {
        this.strokewidthChangeable = value;
    }

    public boolean isSetStrokewidthChangeable() {
        return (this.strokewidthChangeable!= null);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="mutableTemplateImage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="immutableBackgroundImage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="correctionTemplateImage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mutableTemplateImage",
        "immutableBackgroundImage",
        "correctionTemplateImage"
    })
    public static class Images
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        protected String mutableTemplateImage;
        protected String immutableBackgroundImage;
        protected String correctionTemplateImage;

        /**
         * Gets the value of the mutableTemplateImage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMutableTemplateImage() {
            return mutableTemplateImage;
        }

        /**
         * Sets the value of the mutableTemplateImage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMutableTemplateImage(String value) {
            this.mutableTemplateImage = value;
        }

        public boolean isSetMutableTemplateImage() {
            return (this.mutableTemplateImage!= null);
        }

        /**
         * Gets the value of the immutableBackgroundImage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImmutableBackgroundImage() {
            return immutableBackgroundImage;
        }

        /**
         * Sets the value of the immutableBackgroundImage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImmutableBackgroundImage(String value) {
            this.immutableBackgroundImage = value;
        }

        public boolean isSetImmutableBackgroundImage() {
            return (this.immutableBackgroundImage!= null);
        }

        /**
         * Gets the value of the correctionTemplateImage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCorrectionTemplateImage() {
            return correctionTemplateImage;
        }

        /**
         * Sets the value of the correctionTemplateImage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCorrectionTemplateImage(String value) {
            this.correctionTemplateImage = value;
        }

        public boolean isSetCorrectionTemplateImage() {
            return (this.correctionTemplateImage!= null);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="textFieldWidth" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *               &lt;minInclusive value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="textFieldHeight" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *               &lt;minInclusive value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "textFieldWidth",
        "textFieldHeight"
    })
    public static class TextualAnswer
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        protected Integer textFieldWidth;
        protected Integer textFieldHeight;

        /**
         * Gets the value of the textFieldWidth property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getTextFieldWidth() {
            return textFieldWidth;
        }

        /**
         * Sets the value of the textFieldWidth property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setTextFieldWidth(Integer value) {
            this.textFieldWidth = value;
        }

        public boolean isSetTextFieldWidth() {
            return (this.textFieldWidth!= null);
        }

        /**
         * Gets the value of the textFieldHeight property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getTextFieldHeight() {
            return textFieldHeight;
        }

        /**
         * Sets the value of the textFieldHeight property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setTextFieldHeight(Integer value) {
            this.textFieldHeight = value;
        }

        public boolean isSetTextFieldHeight() {
            return (this.textFieldHeight!= null);
        }

    }

}
