//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.03 at 01:32:53 PM MESZ 
//


package de.thorstenberger.taskmodel.complex.complextaskdef;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubTaskDefType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubTaskDefType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="problem" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hint" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="correctionHint" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="interactiveFeedback" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="trash" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="inputLanguage">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="de"/>
 *             &lt;enumeration value="en"/>
 *             &lt;enumeration value="fr"/>
 *             &lt;enumeration value="ru"/>
 *             &lt;enumeration value="es"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubTaskDefType", propOrder = {
    "problem",
    "hint",
    "correctionHint"
})
@XmlSeeAlso({
    ClozeSubTaskDef.class,
    TextSubTaskDef.class,
    McSubTaskDef.class,
    PaintSubTaskDef.class,
    MappingSubTaskDef.class,
    AddonSubTaskDef.class
})
public abstract class SubTaskDefType implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String problem;
    protected String hint;
    protected String correctionHint;
    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute
    protected Boolean interactiveFeedback;
    @XmlAttribute
    protected Boolean trash;
    @XmlAttribute
    protected String inputLanguage;

    /**
     * Gets the value of the problem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProblem() {
        return problem;
    }

    /**
     * Sets the value of the problem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProblem(String value) {
        this.problem = value;
    }

    public boolean isSetProblem() {
        return (this.problem!= null);
    }

    /**
     * Gets the value of the hint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHint() {
        return hint;
    }

    /**
     * Sets the value of the hint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHint(String value) {
        this.hint = value;
    }

    public boolean isSetHint() {
        return (this.hint!= null);
    }

    /**
     * Gets the value of the correctionHint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrectionHint() {
        return correctionHint;
    }

    /**
     * Sets the value of the correctionHint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrectionHint(String value) {
        this.correctionHint = value;
    }

    public boolean isSetCorrectionHint() {
        return (this.correctionHint!= null);
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    public boolean isSetId() {
        return (this.id!= null);
    }

    /**
     * Gets the value of the interactiveFeedback property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isInteractiveFeedback() {
        if (interactiveFeedback == null) {
            return false;
        } else {
            return interactiveFeedback;
        }
    }

    /**
     * Sets the value of the interactiveFeedback property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInteractiveFeedback(boolean value) {
        this.interactiveFeedback = value;
    }

    public boolean isSetInteractiveFeedback() {
        return (this.interactiveFeedback!= null);
    }

    public void unsetInteractiveFeedback() {
        this.interactiveFeedback = null;
    }

    /**
     * Gets the value of the trash property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isTrash() {
        if (trash == null) {
            return false;
        } else {
            return trash;
        }
    }

    /**
     * Sets the value of the trash property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTrash(boolean value) {
        this.trash = value;
    }

    public boolean isSetTrash() {
        return (this.trash!= null);
    }

    public void unsetTrash() {
        this.trash = null;
    }

    /**
     * Gets the value of the inputLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputLanguage() {
        return inputLanguage;
    }

    /**
     * Sets the value of the inputLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputLanguage(String value) {
        this.inputLanguage = value;
    }

    public boolean isSetInputLanguage() {
        return (this.inputLanguage!= null);
    }

}
